spring:
  server:
    port: 8080
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              predicates:
                - Path=/auth/**
              uri:  http://host.docker.internal:8081
  httpclient:
    connect-timeout: 5000   # мс
    response-timeout: 10s   # сек
  filters:
    - name: JwtHeaderFilter
      args:
        order: 1

        # - Retry=5 - Повторяет запросы в случае неудачи


  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: |
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArdLo2RALycceFY9islLK
            iMj2MoS+JqL7lkmVboy91mqnXTKpEwYrEOLuNe+hYUyk/GENYwbyAyn2zusGZ2J8
            TOiDk3yaiqzOY1h+eclFPayBP4On9QqAvjizCYQ2UJzFX4D2zlroJzHM4e2brJH2
            yLO6dG/esEvdbJrnTjF6uc1vc1YQd1G+YgtWE6LgIF8q5Wv8nVmOpbSc1wZOHqnB
            HIr3xor0zPmSHQ0frN/lop6apwb2TRI4/sCJoXuhUhd2Bg86aktisOPp0Cq13o5R
            oiCUnbd4b6QlId8DWkDIWWyAlsCsrESW8IicAF+hEhmnn/5veBK31gYCwGGbGoe8
            WwIDAQAB